DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS seats;
DROP TABLE IF EXISTS flights CASCADE;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS boarding_passes;
DROP TABLE IF EXISTS ticket_flights;
DROP TABLE IF EXISTS airports_data CASCADE;
DROP TABLE IF EXISTS aircrafts_data CASCADE;
DROP FUNCTION IF EXISTS lang;
